### ISSUE TITLE
Order timestamp

### ISSUE THREAD

**Issue by Denise219** [tastefully-simple/cornerstone#11]
### Expected behavior
We would like to see the submitted order timestamp to be Central Time and not in Military time.
Can we also have the Date Stamp to be in Month/Day/Year format?

### Actual behavior
Submitted order displays in Military time and it comes in at Eastern Time.
Date Stamp shows as 12 Nov 2019

### Steps to reproduce behavior
Please a new order - after order appears in BC view the orders area and expand the order details.
View the Date ordered area.

![image](https://user-images.githubusercontent.com/57686045/68800393-9f9f6e00-061f-11ea-8e87-fb78a83a486e.png)

**Comment by mikehoagland** [comment]
Per Bigcommerce: please make the following changes in the store. Go to the Order tab and view the order again:
![unnamed](https://user-images.githubusercontent.com/58264372/69734912-683bc180-10f5-11ea-9d52-5d08e925199a.png)

**Comment by monicakarnes** [comment]
The one below my mailing address and email address can not be formatted at the moment.  It will always be in 24 hour format instead of 12 hour format.  This may change with an upcoming release to the BC control panel, but I don't have a particular timeframe that I can quote.
 
![image](https://user-images.githubusercontent.com/57115301/69744528-f5871200-1105-11ea-891f-70991e9edb38.png)
