### ISSUE TITLE
When signed in as a customer the account drop down menu is down and should only be down when the menu is opened

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#175]
### Expected behavior
When signed in the account drop down menu arrow should be pointing right until the menu is opened: 
![image](https://user-images.githubusercontent.com/57115316/87828133-eba35200-c841-11ea-94ba-bc0623ded9bf.png)

### Actual behavior
When signed in the menu arrow is pointing down before the menu is opened
![image](https://user-images.githubusercontent.com/57115316/87828176-02e23f80-c842-11ea-8953-ee49e2f744fc.png)

### Steps to reproduce behavior
Login to client account, and view the account menu arrow.

**Comment by staciejurczak** [comment]
@suehamre  in a previous design meeting on the menu, I noted that the arrow was recommended to point down due to the hover feature.  With the hover feature there isn't anything going right of the users name. 

![Screen Shot 2020-07-20 at 9 41 12 AM](https://user-images.githubusercontent.com/65304780/87950791-5c7a8200-ca6d-11ea-9ce4-c4bb9350d05c.png)

**Comment by mandi920** [comment]
This is not something we are going to change at this time.
