### ISSUE TITLE
Consultant does not update in the banner, if they attempt to go to closed party link 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#414]
### Expected behavior
Consultant Affiliation Cookie will remain until the client deletes their cookies or chooses a different consultant or party affiliated with another consultant

### Actual behavior
When you have a consultant selected, and a party, or not a party selected.  And you attempt to go to a party link that is closed. You do receive the Darn message the party is closed, but the consultant in your header remains the same. When in fact it should flip to the consultant's who's link you are attempting to view, so you can see their open parties to place your order. 

### Steps to reproduce behavior
I started with clean cookies...
clicked on shop, selected drinks and added chai to my cart
Used modal to find a consultant - selected 2051 Stephanie Cone
Used party bar to select party - Summer Henry - WA 
Then viewed my cart 
![image](https://user-images.githubusercontent.com/57115301/98397461-fff3a080-2024-11eb-8e1f-e6c56a9489c0.png)
Then decided to go to another party link that I have- which is linked to a different consultant  ID 43454 Jennifer Glidden 
FYI- this party is actually closed 
https://tastefully-simple-sandbox-2.mybigcommerce.com/p/10370812
When you go there, you can see the Darn message, the party is closed, but you can see the Consultant in the Header is still for Stephanie, and it also show's Stephanie's open parties. 
![image](https://user-images.githubusercontent.com/57115301/98397725-611b7400-2025-11eb-8d77-484b8436d1e7.png)

I did confirm that it works correctly if the party is actually open --- let me know if you want the details for this part of my testing :)

**Comment by jsmnglng-w** [comment]
@monicakarnes This is what I was told to do: "If there's already an affiliated consultant, and you look up a party and it's closed, nothing should change with the consultant association nor the party association."

Also, if that's the expected behavior (affiliated consultant that remains should be the consultant with the closed party right?), I don't have a way to grab the consultant that is affiliated to the closed party because the party details API only shows "Party has been closed." whenever we ask for a closed party. So I don't have enough data to display the expected consultant.

Here's the API returning data for a closed party:

<img width="1211" alt="Screen Shot 2020-11-06 at 2 52 16 PM" src="https://user-images.githubusercontent.com/69249028/98414729-828a5900-2041-11eb-9d32-b97bcf701bed.png">

**Comment by TastefullySimple** [comment]
The are business cases to change any affiliation if the party is closed.
